spring.application.name=demo
server.port=8081

# H2 In-Memory Database (Development)
spring.datasource.url=jdbc:h2:mem:funzonedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dev redirect base
wechat.appid=
wechat.appsecret=
wechat.redirect-base=http://localhost:${server.port}

